### ISSUE TITLE
Missing Requests on Dashboard

### ISSUE THREAD

**Issue by umairkhan-10** [tom-draper/api-analytics#17] opened 2023-07-26 06:31 UTC
There's an issue with logging requests in analytics dashboard.

Sometimes it captures all of the incoming requests, sometimes it doesn't 

Usually, when I request same api 5, 6 times, it misses some requests hence not logging all of the requests.
I tried generating new API key to see if the issue is with the key and also tried to install 1.1.3 version but didn't help.

**Comment by tom-draper** [comment] 2023-07-26 08:18
Hi, thanks for letting me know. What web framework are you using and how are you hosting your API? I'm aware of issues with requests appearing on the dashboard very inconsistently when hosting with serverless platforms like Vercel and I'm trying to find a good solution

**Comment by umairkhan-10** [comment] 2023-07-26 10:55
I'm using FastAPI as well.
For hosting, I've hosted my server on EC2 over nginx, supervisor and Gunicorn.

**Comment by tom-draper** [comment] 2023-09-28 12:57
Closing this issue as it should be solved now. The issue was caused by the server ratelimiter failing to access the correct IP address. The ratelimiter is now based on API key.

**Closed by tom-draper** 2023-09-28 12:57 UTC
